
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Roboto } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/app/components/ThemeProvider";
import Lenis  from "lenis";
import SmoothScrolling from "./components/SmoothScrolling";

const roboto = Roboto({
  subsets: ['latin'],
  variable: "--font-roboto-sans"
})
const inter = Inter({
  subsets: ['latin'], display: 'swap'
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} ${geistMono.variable} h-full antialiased tracking-wider`}
      suppressHydrationWarning={true}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScrolling>
          <Providers>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              {children}
            </ThemeProvider>
          </Providers>
        </SmoothScrolling>
        <Toaster position="top-right" richColors={true} />
      </body>
    </html>
  );
}
