"use client";

import { useAdminKycs, useModerateKyc } from "@/app/hooks/useAdmin";
import { AdminKycRecord } from "@/app/services/adminService";
import { toast } from "sonner";

export default function KycManagement() {
    const { data = [], isLoading, isError, refetch } = useAdminKycs();
    const moderate = useModerateKyc();
    const update = async (kyc: AdminKycRecord, status: "APPROVED" | "REJECTED") => { try { await moderate.mutateAsync({ kycId: kyc.kycId, status }); toast.success(`KYC ${status.toLowerCase()}`); } catch { toast.error("Unable to update KYC status"); } };
    return <section className="space-y-5"><div className="flex items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">KYC review</h1><p className="mt-1 text-sm text-slate-500">Review verification applications and make a decision.</p></div><button onClick={() => refetch()} className="rounded-lg border px-3 py-2 text-sm">Refresh</button></div>{isLoading ? <p className="text-sm text-slate-500">Loading KYC records…</p> : isError ? <p className="text-sm text-rose-600">Unable to load KYC records. <button onClick={() => refetch()} className="underline">Retry</button></p> : data.length === 0 ? <p className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">No KYC applications to review.</p> : <div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-900"><tr><th className="p-3">Applicant</th><th className="p-3">Document</th><th className="p-3">Submitted</th><th className="p-3">Status</th><th className="p-3" /></tr></thead><tbody>{data.map(kyc => <tr key={kyc.kycId} className="border-t border-slate-100 dark:border-slate-800"><td className="p-3"><div className="font-medium">{[kyc.firstName, kyc.middleName, kyc.lastName].filter(Boolean).join(" ") || kyc.user?.email || "—"}</div><div className="text-xs text-slate-500">{kyc.user?.email}</div></td><td className="p-3">{kyc.documentType || "—"}</td><td className="p-3">{kyc.submittedAt ? new Date(kyc.submittedAt).toLocaleDateString() : "—"}</td><td className="p-3">{kyc.kycStatus}</td><td className="p-3 text-right">{kyc.kycStatus === "PENDING" && <span className="inline-flex gap-2"><button disabled={moderate.isPending} onClick={() => update(kyc, "REJECTED")} className="rounded-lg border px-3 py-1.5 text-xs text-rose-600">Reject</button><button disabled={moderate.isPending} onClick={() => update(kyc, "APPROVED")} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs text-white">Approve</button></span>}</td></tr>)}</tbody></table></div>}</section>;
}
