"use client";

import { useAdminProperties, useModerateProperty } from "@/app/hooks/useAdmin";
import { AdminPropertyResponse } from "@/app/services/adminService";
import { toast } from "sonner";

export default function PropertyManagement() {
    const { data = [], isLoading, isError, refetch } = useAdminProperties();
    const moderate = useModerateProperty();
    const update = async (property: AdminPropertyResponse) => { const status = property.propertyStatus === "BLOCKED_BY_ADMIN" ? "ACTIVE" : "BLOCKED_BY_ADMIN"; try { await moderate.mutateAsync({ propertyId: property.id, status }); toast.success(`Property ${status === "ACTIVE" ? "reinstated" : "blocked"}`); } catch { toast.error("Unable to update property status"); } };
    return <section className="space-y-5"><div className="flex items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">Properties</h1><p className="mt-1 text-sm text-slate-500">Review listings and moderate their visibility.</p></div><button onClick={() => refetch()} className="rounded-lg border px-3 py-2 text-sm">Refresh</button></div>{isLoading ? <p className="text-sm text-slate-500">Loading properties…</p> : isError ? <p className="text-sm text-rose-600">Unable to load properties. <button onClick={() => refetch()} className="underline">Retry</button></p> : data.length === 0 ? <p className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">No properties are available for review.</p> : <div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-900"><tr><th className="p-3">Property</th><th className="p-3">Country</th><th className="p-3">Rooms</th><th className="p-3">Status</th><th className="p-3" /></tr></thead><tbody>{data.map(property => <tr key={property.id} className="border-t border-slate-100 dark:border-slate-800"><td className="p-3"><div className="font-medium">{property.propertyName}</div><div className="text-xs text-slate-500">{property.description || "No description"}</div></td><td className="p-3">{property.country || "—"}</td><td className="p-3">{property.totalRooms ?? 0}</td><td className="p-3">{property.propertyStatus}</td><td className="p-3 text-right"><button disabled={moderate.isPending} onClick={() => update(property)} className="rounded-lg border px-3 py-1.5 text-xs font-medium disabled:opacity-50">{property.propertyStatus === "BLOCKED_BY_ADMIN" ? "Reinstate" : "Block"}</button></td></tr>)}</tbody></table></div>}</section>;
}
